"use client";

import {
  Container,
  Title,
  Text,
  Image,
  Stack,
  Badge,
  Group,
  Divider,
  TypographyStylesProvider,
  Skeleton,
  Button,
  Box,
  Paper,
} from "@mantine/core";
import { useGetBlogBySlugQuery } from "@/services/blogApi";

import { Calendar, User, ArrowLeft, Home } from "lucide-react";
import Link from "next/link";

interface BlogDetailClientProps {
  slug: string;
}

export default function BlogDetailClient({ slug }: BlogDetailClientProps) {
  // 1. Fetch Blog Content
  const { data: blog, isLoading: blogLoading } = useGetBlogBySlugQuery(slug);

  if (blogLoading)
    return (
      <Container size="xl" py={100} px={{ base: 8, md: 12, lg: 16 }}>
        <Skeleton height={400} radius="md" />
      </Container>
    );

  if (!blog)
    return (
      <Container
        size="xl"
        py={100}
        ta="center"
        px={{ base: 8, md: 12, lg: 16 }}
      >
        <Title>Guide not found</Title>
      </Container>
    );

  return (
    <Container size="xl" py={80} px={{ base: 8, md: 12, lg: 16 }}>
      <Button
        component={Link}
        href="/admin-dashboard/blogs"
        color="#4161df"
        variant="subtle"
        leftSection={<ArrowLeft size={16} />}
        mb="xl"
      >
        Back to Blogs
      </Button>

      <Stack gap="lg">
        <Badge size="lg" variant="filled" color="#4161df">
          {blog.category}
        </Badge>

        <Title order={1} size="42px" fw={900} style={{ lineHeight: 1.1 }}>
          {blog.title}
        </Title>

        <Group gap="xl" c="dimmed">
          <Group gap={5}>
            <Calendar size={18} />
            <Text size="sm">
              {new Date(blog.createdAt).toLocaleDateString("en-IN")}
            </Text>
          </Group>
          <Group gap={5}>
            <User size={18} />
            <Text size="sm">Ink of Memories Editorial</Text>
          </Group>
        </Group>

        <Image
          src={
            blog.image ||
            "https://images.unsplash.com/photo-1590066305974-26999a08ec40?q=80&w=1200"
          }
          radius="md"
          alt={blog.title}
          h={200}
          w="100%"
        />

        {/* This renders the HTML generated by your AI */}
        <TypographyStylesProvider p={0} mt="xl">
          <div dangerouslySetInnerHTML={{ __html: blog.content }} />
        </TypographyStylesProvider>
      </Stack>
    </Container>
  );
}
